name: Development deployment
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install project
        run: |
          npm install -g yarn
          yarn
          yarn build
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
        with:
          source: "./"
          target: "/var/www/next/app-tmp"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
          script: |
            pm2 stop next-js
            mv /var/www/next/app /var/www/next/app-del
            mv /var/www/next/app-tmp /var/www/next/app
            pm2 start next-js
            rm -rf /var/www/next/app-del
